// Extracts glyph outlines, advances and pair kerning for CHARSET from the pinned IBM Plex Sans
// OTFs and writes them as TypeScript modules, so the renderer outlines text without shipping or
// parsing a font at runtime. Run after changing CHARSET or the font files:
//   pnpm glyphs:build          regenerate src/font/*.generated.ts
//   pnpm glyphs:check          fail if the generated modules are out of date (CI)
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import opentype from 'opentype.js';
import { CHARSET } from '../src/font/charset.ts';

interface Face {
  file: string;
  module: string;
  exportName: string;
}

const FACES: Face[] = [
  { file: 'IBMPlexSans-Regular.otf', module: 'sans-regular', exportName: 'SANS_REGULAR' },
  { file: 'IBMPlexSans-Bold.otf', module: 'sans-bold', exportName: 'SANS_BOLD' },
];

const here = (path: string) => new URL(`../${path}`, import.meta.url);

/** Font units are integers in these OTFs; keep up to two decimals should that ever change. */
function num(value: number): string {
  const rounded = Math.round(value * 100) / 100;
  return Object.is(rounded, -0) ? '0' : String(rounded);
}

function encodePath(commands: opentype.PathCommand[]): string {
  let d = '';
  for (const c of commands) {
    switch (c.type) {
      case 'M':
      case 'L':
        d += `${c.type}${num(c.x)} ${num(c.y)}`;
        break;
      case 'C':
        d += `C${num(c.x1)} ${num(c.y1)} ${num(c.x2)} ${num(c.y2)} ${num(c.x)} ${num(c.y)}`;
        break;
      case 'Q':
        // CFF outlines are cubic. Fail loudly if a TrueType source is ever swapped in, so
        // consumers (PDF export included) can keep relying on M, L, C and Z only.
        throw new Error('Quadratic outline found; expected CFF (cubic) outlines');
      case 'Z':
        d += 'Z';
        break;
    }
  }
  return d;
}

function generate(face: Face): string {
  const bytes = readFileSync(here(`fonts/${face.file}`));
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  const font = opentype.parse(
    bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength),
  );
  const family = font.names.windows?.fontFamily?.en ?? 'IBM Plex Sans';
  const subfamily = font.names.windows?.fontSubfamily?.en ?? '';
  const version = (font.names.windows?.version?.en ?? '').replace(/^Version\s+/, '');
  const os2 = font.tables.os2;

  const chars = [...CHARSET];
  const glyphs = chars.map((ch) => {
    const glyph = font.charToGlyph(ch);
    if (!glyph || glyph.index === 0)
      throw new Error(`${face.file} has no glyph for U+${ch.codePointAt(0)!.toString(16)}`);
    return { ch, glyph };
  });

  const glyphLines = glyphs.map(
    ({ ch, glyph }) =>
      `    ${JSON.stringify(ch)}: [${num(glyph.advanceWidth ?? 0)}, ${JSON.stringify(encodePath(glyph.path.commands))}],`,
  );

  const kernLines: string[] = [];
  for (const left of glyphs) {
    for (const right of glyphs) {
      const value = font.getKerningValue(left.glyph, right.glyph);
      if (value !== 0) kernLines.push(`    ${JSON.stringify(left.ch + right.ch)}: ${num(value)},`);
    }
  }

  return [
    '// GENERATED by scripts/build-glyphs.ts. Do not edit by hand.',
    `// Outlines and metrics derived from ${family} ${subfamily}, version ${version}`,
    `// (${face.file}, SHA-256 ${sha256}).`,
    '// Copyright © 2017 IBM Corp. with Reserved Font Name "Plex". Licensed under the',
    '// SIL Open Font License 1.1; see packages/panel/fonts/OFL.txt.',
    "import type { FontData } from './types.ts';",
    '',
    `export const ${face.exportName}: FontData = {`,
    `  name: ${JSON.stringify(`${family} ${subfamily} ${version}`)},`,
    `  unitsPerEm: ${font.unitsPerEm},`,
    `  capHeight: ${os2.sCapHeight},`,
    `  xHeight: ${os2.sxHeight},`,
    '  glyphs: {',
    ...glyphLines,
    '  },',
    '  kerning: {',
    ...kernLines,
    '  },',
    '};',
    '',
  ].join('\n');
}

const check = process.argv.includes('--check');
let stale = false;
for (const face of FACES) {
  const target = here(`src/font/${face.module}.generated.ts`);
  const source = generate(face);
  if (check) {
    let current = '';
    try {
      current = readFileSync(target, 'utf8');
    } catch {}
    if (current !== source) {
      console.error(`src/font/${face.module}.generated.ts is out of date; run pnpm glyphs:build`);
      stale = true;
    }
  } else {
    writeFileSync(target, source);
    console.log(
      `wrote src/font/${face.module}.generated.ts (${(source.length / 1024).toFixed(0)} KB)`,
    );
  }
}
if (stale) process.exit(1);
