/**
 * Outline and metric data for one typeface weight, in font units (y axis up).
 * Generated by scripts/build-glyphs.ts from the OTFs in packages/panel/fonts.
 */
export interface FontData {
  /** Human-readable face name and version, recorded in generated artwork metadata. */
  readonly name: string;
  readonly unitsPerEm: number;
  readonly capHeight: number;
  readonly xHeight: number;
  /** Advance width and outline path (absolute M, L, C and Z commands) per character. */
  readonly glyphs: Readonly<Record<string, readonly [advance: number, path: string]>>;
  /** Pair kerning adjustments keyed by the two characters, e.g. "AV". Zero pairs are omitted. */
  readonly kerning: Readonly<Record<string, number>>;
}
